<a href="https://colab.research.google.com/github/mhaamzaa/Machine-Learning-in-90-days/blob/master/PythonD2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas Tutorial
Pandas is an open source, BSD-licensed library providing high-performance,
easy-to-use data structures and data analysis tools for the Python programming language.

###Agenda
*   What is Data Frames?
*   What is Data Series?
*   Different operation in Pandas

In [52]:
import numpy as np
import pandas as pd

In [53]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index = ['row1', 'row2', 'row3', 'row4','row5'], columns = ['C1','C2', 'C3','C4'])

In [54]:
df.head()

      C1  C2  C3  C4
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [55]:
df.to_csv("test1.csv")

In [56]:
df.to_excel("test1.xlsx")

## Indexing
* loc
* iloc

### loc:
it is for just row indexing
### iloc:
it is for both row and column indexing

In [57]:
df.loc['row1']

C1    0
C2    1
C3    2
C4    3
Name: row1, dtype: int64

In [58]:
type(df.loc['row1'])

pandas.core.series.Series

In [59]:
df.iloc[1:2,1:3]

      C2  C3
row2   5   6

In [60]:
type(df.iloc[0:2,0])

pandas.core.series.Series

In [61]:
df.iloc[0:2,0]

row1    0
row2    4
Name: C1, dtype: int64

In [62]:
## to array
df.iloc[0:2 ,1:4]. values

array([[1, 2, 3],
       [5, 6, 7]])

In [63]:
df.iloc[0:2 ,1:4]. values.shape

(2, 3)

In [64]:
df.isnull().sum
df['C1'].unique

<bound method Series.unique of row1     0
row2     4
row3     8
row4    12
row5    16
Name: C1, dtype: int64>

In [65]:
df[['C1', 'C4']]

      C1  C4
row1   0   3
row2   4   7
row3   8  11
row4  12  15
row5  16  19

In [66]:
url = 'https://github.com/krishnaik06/Machine-Learning-in-90-days/blob/3913bd6f5e1db16d66b425ac216c2212f3ba44ca/Section%201-%20Python%20Crash%20Course/mercedesbenz.csv'

In [68]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [69]:
df = pd.read_csv('/content/drive/MyDrive/Python_DS/mercedesbenz.csv')

In [70]:
df.tail()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [72]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [74]:
df['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

## CSV

In [75]:
from io import StringIO, BytesIO

In [89]:
data = ('col1, col2,col3\n'
'3,5,1\n'
'8,6,7\n'
'0,2,9')

In [87]:
type(data)

str

In [90]:
pd.read_csv(StringIO(data), dtype =int )

   col1   col2  col3
0     3      5     1
1     8      6     7
2     0      2     9